import { Component } from '@angular/core';

@Component({
  selector: 'even-fibonacci-numbers',
  templateUrl: 'even-fibonacci-numbers.component.html',
  styleUrls: ['even-fibonacci-numbers.component.css']
})
export class EvenFibonacciNumbersComponent {
  problemDescription = 'Each new term in the Fibonacci sequence is generated by adding the previous two terms. ' +
    'By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the ' +
    'terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.';
  solution: number;

  constructor() {
    this.solution = this.findEvenFibonacciNumbers(4000000);
  }

  findEvenFibonacciNumbers(limit:number): number{
    let sum: number = 0;
    let next: number = 0;
    for(let i =0; next < limit; i++) {
      next = this.fibonacciRecursive(i);
      if (this.isEven(next)){
        sum+=next;
      }
    }
    return sum;
  }

  fibonacciRecursive(limit:number){
    if(limit <= 2){
      return limit;
    }
    return this.fibonacciRecursive(limit-2) + this.fibonacciRecursive(limit-1);
  }

  isEven(intToCheck:number):boolean{
    return intToCheck%2 == 0;
  }
}
